//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garage
    {
        public int idGarage_pk_ { get; set; }
        public int idOwnersAndTheirCars_fk_ { get; set; }
        public int theGuardWhoPut_fk_ { get; set; }
        public System.DateTime dateOfPuttingTheCarInTheGarage { get; set; }
        public Nullable<System.DateTime> dateOfTakingTheCarIntoTheGarage { get; set; }
        public Nullable<int> theGuardWhoGaveOut_fk_ { get; set; }
    
        public virtual OwnersAndTheirCars OwnersAndTheirCars { get; set; }
        public virtual Watchman Watchman { get; set; }
        public virtual Watchman Watchman1 { get; set; }
    }
}
